version: "3.8"

services:
  reserva-sala:
    container_name: reserva-sala
    build: .
    ports:
      - "8088:8080"
    env_file:
      - .env
    # volumes:
    #   - .:/app  # Remover em produção para não sobrescrever o build do container
    restart: unless-stopped
    networks:
      - miner

networks:
  miner:
    external: true
